### ISSUE TITLE
关于 clojure-china.org

### ISSUE THREAD

**Issue by xhh** [clojure-china/faq#1]

**Comment by jiacai2050** [comment]
虽然知道会有这么一天，还是有些痛心。😭
同为小众的 [Emacs China](https://emacs-china.org/) 是我觉得国内少有的优秀论坛，提问、回答都跟正规，也不断有耳目一新的帖子出来，让我眼前一亮，还能这么玩呀！

感谢站长之前的付出，建议把这个域名重定向到[豆瓣 clojure 小组](https://www.douban.com/group/159669/)，也算是个归宿。

**Comment by guenchi** [comment]
我有一个自己搭建的主机，位于欧洲千兆光纤上。希望能将站点转移过来。

不然太可惜咯

**Comment by xhh** [comment]
@jiacai2050 Emacs China 社区的确很优秀. 最近在讨论看有没有人愿意接手维护论坛, 如果最后没有人维护的话, 会把域名重定向到其他 Clojure 相关域名.

@guenchi 你用微信吗? 用的话可以把你的微信号发送到我的邮箱 xhh@xhh.me
然后我邀请你进群聊, 讨论转移论坛的事情.
